# TCL File Generated by Component Editor 18.1
# Sat Nov 23 14:17:16 KRAT 2019
# DO NOT MODIFY


# 
# ram_avalon "ram_avalon" v1.0
# Dmitriy0111(Vlasov D.V.) 2019.11.23.14:17:16
# ram module with avalon interface
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1
source $env(QUARTUS_ROOTDIR)/../ip/altera/sopc_builder_ip/common/embedded_ip_hwtcl_common.tcl

# 
# module ram_avalon
# 
set_module_property DESCRIPTION "ram module with avalon interface"
set_module_property NAME ram_avalon
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Processors and Peripherals/Peripherals"
set_module_property AUTHOR "Dmitriy0111(Vlasov D.V.)"
set_module_property DISPLAY_NAME ram_avalon
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property ELABORATION_CALLBACK elaborate

# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ram_avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ram.sv SYSTEM_VERILOG PATH ../ram_avalon/ram.sv
add_fileset_file ram_avalon.sv SYSTEM_VERILOG PATH ../ram_avalon/ram_avalon.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL ram_avalon
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file ram.sv SYSTEM_VERILOG PATH ../ram_avalon/ram.sv
add_fileset_file ram_avalon.sv SYSTEM_VERILOG PATH ../ram_avalon/ram_avalon.sv

# 
# parameters
# 

add_parameter depth INTEGER 64
set_parameter_property depth DEFAULT_VALUE 64
set_parameter_property depth DISPLAY_NAME "Memory size in bytes"
set_parameter_property depth TYPE INTEGER
set_parameter_property depth UNITS None
set_parameter_property depth ALLOWED_RANGES -2147483648:2147483647
set_parameter_property depth HDL_PARAMETER true

add_parameter init INTEGER 0
set_parameter_property init DEFAULT_VALUE 0
set_parameter_property init DISPLAY_NAME init
set_parameter_property init TYPE INTEGER
set_parameter_property init UNITS None
set_parameter_property init ALLOWED_RANGES 0:3
set_parameter_property init HDL_PARAMETER true

add_parameter path2file STRING "path to hex file"
set_parameter_property path2file DEFAULT_VALUE "path to hex file"
set_parameter_property path2file DISPLAY_NAME path2file
set_parameter_property path2file TYPE STRING
set_parameter_property path2file UNITS None
set_parameter_property path2file HDL_PARAMETER true

# 
# display items
# 

proc elaborate {} {
    set depth [ get_parameter_value depth ]
    set new_depth [ expr { $depth / 4 } ]
    set addr_width [ expr [ log2ceil $new_depth ] ]

    # 
    # connection point clk
    # 
    add_interface clk clock end
    set_interface_property clk clockRate 0
    set_interface_property clk ENABLED true
    set_interface_property clk EXPORT_OF ""
    set_interface_property clk PORT_NAME_MAP ""
    set_interface_property clk CMSIS_SVD_VARIABLES ""
    set_interface_property clk SVD_ADDRESS_GROUP ""

    add_interface_port clk clk clk Input 1

    # 
    # connection point s_0
    # 
    add_interface s_0 avalon end
    set_interface_property s_0 addressUnits WORDS
    set_interface_property s_0 associatedClock clk
    set_interface_property s_0 associatedReset reset
    set_interface_property s_0 bitsPerSymbol 8
    set_interface_property s_0 burstOnBurstBoundariesOnly false
    set_interface_property s_0 burstcountUnits WORDS
    set_interface_property s_0 explicitAddressSpan 0
    set_interface_property s_0 holdTime 0
    set_interface_property s_0 linewrapBursts false
    set_interface_property s_0 maximumPendingReadTransactions 0
    set_interface_property s_0 maximumPendingWriteTransactions 0
    set_interface_property s_0 readLatency 0
    set_interface_property s_0 readWaitTime 1
    set_interface_property s_0 setupTime 0
    set_interface_property s_0 timingUnits Cycles
    set_interface_property s_0 writeWaitTime 0
    set_interface_property s_0 ENABLED true
    set_interface_property s_0 EXPORT_OF ""
    set_interface_property s_0 PORT_NAME_MAP ""
    set_interface_property s_0 CMSIS_SVD_VARIABLES ""
    set_interface_property s_0 SVD_ADDRESS_GROUP ""

    add_interface_port s_0 address address Input $addr_width
    add_interface_port s_0 chipselect chipselect Input 1
    add_interface_port s_0 write write Input 1
    add_interface_port s_0 byteenable byteenable Input d_width/size
    add_interface_port s_0 writedata writedata Input d_width
    add_interface_port s_0 readdata readdata Output d_width
    set_interface_assignment s_0 embeddedsw.configuration.isFlash 0
    set_interface_assignment s_0 embeddedsw.configuration.isMemoryDevice 0
    set_interface_assignment s_0 embeddedsw.configuration.isNonVolatileStorage 0
    set_interface_assignment s_0 embeddedsw.configuration.isPrintableDevice 0

    # 
    # connection point reset
    # 
    add_interface reset reset end
    set_interface_property reset associatedClock clk
    set_interface_property reset synchronousEdges DEASSERT
    set_interface_property reset ENABLED true
    set_interface_property reset EXPORT_OF ""
    set_interface_property reset PORT_NAME_MAP ""
    set_interface_property reset CMSIS_SVD_VARIABLES ""
    set_interface_property reset SVD_ADDRESS_GROUP ""

    add_interface_port reset reset reset Input 1
}
